version: "3"
services:
  message:
    build: message/
    ports:
      - "9010:9010"
    links:
      - messageapp
      - mongodb_message
      - replica_message
      - redis
    depends_on:
      - messageapp
      - mongodb_message
      - replica_message
      - redis
  credit:
    build: credit/
    ports:
      - "9020:9020"
    links:
      - mongodb_credit
      - replica_credit
      - redis
    depends_on:
      - mongodb_credit
      - replica_credit
      - redis
  messageapp:
    image: cabify/backend-bootcamp-messageapp:exercise10
    ports:
      - "3000:3000"

  mongodb_credit:
    image: mongo
    command: mongod --port 27017
    volumes:
      - ./credit/data/db:/credit/data/db
    ports:
      - 27017:27017
  replica_credit:
    image: mongo
    command: mongod --port 27018
    volumes:
      - ./credit/data/replica:/credit/data/replica
    ports:
      - 27018:27018

  mongodb_message:
    image: mongo
    command: mongod --port 27027
    volumes:
      - ./message/data/db:/message/data/db
    ports:
      - 27027:27027
  replica_message:
    image: mongo
    command: mongod --port 27028
    volumes:
      - ./message/data/replica:/message/data/replica
    ports:
      - 27028:27028
  redis:
    image: redis
    ports:
      - 6379:6379
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus-grafana/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./prometheus-grafana/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./prometheus-grafana/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    ports:
      - 4000:3000
    links:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
  # node-exporter:
  #   image: prom/node-exporter:latest
  #   container_name: monitoring_node_exporter
  #   restart: unless-stopped
  #   expose:
  #     - 9100

# GF_SECURITY_ADMIN_PASSWORD=admin
# GF_USERS_ALLOW_SIGN_UP=false

  # prometheus:
  #   image: prom/prometheus:latest
  #   volumes:
  #     - ~/prometheus-grafana/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - 9090:9090
  # grafana:
  #   image: grafana/grafana:latest
  #   volumes:
  #     - ~/prometheus-grafana/grafana/grafana.ini:/etc/grafana/grafana.ini
  #     - ~/prometheus-grafana/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
  #   ports:
  #     - 4000:4000
  #   links:
  #     - prometheus
      # environment:
      # - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      # - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      # - GF_USERS_ALLOW_SIGN_UP=false
      



  # prom:
  #   image: prom/prometheus:v2.27.1
  #   ports:
  #     - 9090:9090
  # grafana:
  #   image: grafana/grafana:7.5.7
  #   ports:
  #     - 4000:4000



  # grafana:
  #   image: grafana/grafana:6.7.2
  #   container_name: grafana
  #   volumes:
  #     - grafana_data:/var/lib/grafana
  #     - ./grafana/provisioning:/etc/grafana/provisioning
  #   environment:
  #     - GF_SECURITY_ADMIN_USER=${ADMIN_USER}
  #     - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
  #     - GF_USERS_ALLOW_SIGN_UP=false
  #   restart: unless-stopped
  #   expose:
  #     - 3000
  #   networks:
  #     - monitor-net
  #   labels:
  #     org.label-schema.group: "monitoring"  